### ISSUE TITLE
[Question] Is there a size limit of bgeo you can read?

### ISSUE THREAD

**Issue by cchampet** [dkoerner/houio#5]
Hello,
First thank you for your simple yet powerful library to manipulate caches!
I have an issue when I run this following code, with a bgeo file of about 8.6G:
```c++
std::ifstream in( filename.c_str(), std::ios_base::in | std::ios_base::binary );
houio::HouGeo::Ptr houGeo;
houGeo = houio::HouGeoIO::import(&in);
```
The import raises an __std::bad_alloc__.

Is this case a known issue? Thank you for your time.
Cheers,

**Comment by nrondaud** [comment]
Hey Clément,

I encountered the same problem.
From what I see, there is no hard-coded limitation or anything else like that, but a simple integer overflow issue when loading a large dataset.
I made a super-quick fix which (in my case) seems to solve the problem. Please take a look at the following PR #6.

I hope it will solve your problem too :)

**Comment by dkoerner** [comment]
Thanks @nrondaud  for fixing this 👍
